### ISSUE TITLE
buttons in reminder tab don't work

### ISSUE THREAD

**Issue by sou-c** [dsi-icl/optimise#65] opened 2018-04-20 15:49 UTC
When 'on' is pressed, a new entry is created. however when the 'on' button on this second entry is pressed nothing happens. If i proceed to delete the first entry, the only entry left is stuck in a permanently 'on' state

**Comment by epissari** [comment] 2018-04-20 16:52
Possible duplicate of issue #32 which has been fixed in candidate branch `fixes-oxford-april` commit 62d14b5db048ca3da57d74f84168d46487ff875 ?

**Comment by epissari** [comment] 2018-04-24 09:44
Fix proposed in commit 08c1d678c4900dc0f2d917504a88b3712cef3f4d.

**Closed by epissari** 2018-04-24 09:44 UTC
Labels: bug
