### ISSUE TITLE
UX: showing empty disabled fields for treatments, tests and visits when no such entry is selected

### ISSUE THREAD

**Issue by sou-c** [dsi-icl/optimise#63] opened 2018-04-20 15:28 UTC
I think users like me instinctively go to enter data to the fields (only to be shown the field is disabled) without realising they have to go create a new entry first

**Comment by fguitton** [comment] 2018-04-24 08:47
I believe this is duplicate of #64. And a fix was proposed there so I am closing this issue. @sou-c If you think this is not satisfactory please reopen the issue.

**Closed by fguitton** 2018-04-24 08:47 UTC
Labels: enhancement
